# Stage 1: Build
FROM node:20-alpine AS build
WORKDIR /app
ARG NG_APP_BACKEND_BASE=http://localhost:8038
ENV NG_APP_BACKEND_BASE=${NG_APP_BACKEND_BASE}
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# Stage 2: Serve
FROM nginx:alpine
COPY --from=build /app/dist/datalab-frontend/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
